#!/bin/bash

# Menggunakan tput untuk menambahkan warna
GREEN=$(tput setaf 2)    # Hijau
RED=$(tput setaf 1)      # Merah
YELLOW=$(tput setaf 3)   # Kuning
NC=$(tput sgr0)          # Tidak ada warna (reset)

# Fungsi untuk mencetak garis pemisah
print_line() {
    echo -e "${YELLOW}========================================${NC}"
}

# Judul
print_line
echo -e "${YELLOW}           Service Status               ${NC}"
print_line

# Fungsi untuk memeriksa status container Docker Marzban
check_container_status() {
    local container_name="marzban-marzban-1"
    local status=$(docker inspect -f '{{.State.Running}}' "$container_name" 2>/dev/null)
    if [ "$status" == "true" ]; then
        echo -e "${GREEN}✔ Marzban is running.${NC}"
    else
        echo -e "${RED}✘ Marzban is not running.${NC}"
    fi
}

# Fungsi untuk memeriksa status WARP
check_warp_status() {
    local status=$(systemctl is-active wireproxy)
    if [ "$status" == "active" ]; then
        echo -e "${GREEN}✔ WARP is active.${NC}"
    else
        echo -e "${RED}✘ WARP is not active.${NC}"
    fi
}

# Fungsi untuk memeriksa status Fix Instances service
check_fix_instances_status() {
    local status=$(systemctl is-active fix.service)
    if [ "$status" == "active" ]; then
        echo -e "${GREEN}✔ Fix Instances is active.${NC}"
    else
        echo -e "${RED}✘ Fix Instances is not active.${NC}"
    fi
}

# Cek status container Docker Marzban
check_container_status

# Cek status WARP
check_warp_status

# Cek status Fix Instances service
check_fix_instances_status

# Garis bawah
print_line
