#!/bin/bash

container_name="marzban-marzban-1"  # Nama container Marzban

while true; do
    if docker logs "$container_name" --tail 5 2>&1 | grep -q "maximum number of running instances reached"; then
        echo "Pesan terdeteksi, melakukan restart Marzban..."
        docker restart "$container_name"
        sleep 60  # Tunggu sebentar sebelum melanjutkan pemantauan
    fi
    sleep 60  # Interval waktu pengecekan
done
